### ISSUE TITLE
We need to design a logo and find a way to order them

### ISSUE THREAD

**Issue by Andersos** [nodeschool/oslo#1]
Make a logo

You can use this .AI/.SVG template to design your own custom nodeschool sticker/logo.
https://github.com/nodeschool/nodeschool.github.io/tree/master/images/make-a-sticker

**Comment by asbjornenge** [comment]
I recently tried ordering som stickers from Sticker Mule to Norway, and they have been stuck in customs for 2 weeks+ !? Dunno why. Last order was the same. AND, they have changed the cost of shipping to international location to $49 :disappointed: 

If you guys find another place to order (or go for Sticker Mule anyway) we would love to order some for the Stavanger Nodeschool chapter too (we already have a logo made) and split the shipping :smile_cat: 

Also; no/en?

**Comment by Andersos** [comment]
Cool. Yeah, when/if we get the logo made we can definitively split the shipping costs if that makes sense. I have not checked out Sticker Mule yet but they sound like the right place to go =)

**Comment by finnp** [comment]
We haven't ordered stickers yet in Berlin. But we started a list which includes world-wide providers: https://github.com/nodeschool/berlin/issues/3 . I think I am going to try diginate.

**Comment by Andersos** [comment]
@finnp cool thanks for the list :+1:

**Comment by asbjornenge** [comment]
@finnp awesome! Diginate looks great :tada:
@Andersos Let me know what happens :rocket:

**Comment by maciejczyzewski** [comment]
We have a logo? :blush:

![sticker](https://dl.dropboxusercontent.com/u/103345209/Screenshots/Screenshot%202015-01-28%2019.35.05.png)

[SVG](https://dl.dropboxusercontent.com/u/103345209/nodeschool-sticker-oslo.svg)
[PNG](https://dl.dropboxusercontent.com/u/103345209/Screenshots/Screenshot%202015-01-28%2019.35.05.png)

---

Are you going to continue "nodeschool oslo" event?

**Comment by Andersos** [comment]
Cool logo =)
