### ISSUE TITLE
Another nodescool event in Oslo?

### ISSUE THREAD

**Issue by mewwts** [nodeschool/oslo#3]
Been a while since the last one.

**Comment by Andersos** [comment]
Sure, let us see if we can find a place to be =)

**Comment by mewwts** [comment]
Cool :+1:

**Comment by Andersos** [comment]
Do you have any suggestions?

**Comment by mewwts** [comment]
Teknologihuset should be doable? Last time at Finn was good too. Also I suggest the stream-adventure workshop.

**Comment by Andersos** [comment]
Maybe you can contact Teknologihuset and find some fitting dates?
Looks like there will be an [international NodeSchool](https://github.com/nodeschool/international-day) event in May.

**Comment by mewwts** [comment]
I'd be happy to do it after easter, but right now it's a bit too crazy.

**Comment by ghost** [comment]
Grüetziwohl! @mewwts spoke to me at OneShot NodeConf about a possible event in autumm. So I'll go ahead and propose saturday the 26th of September as a date. How's everybody with that? Exactly three months from now, and exactly one year after the first event.

I'd like to work a little bit with ES6, preferrably together with _iojs_, and could maybe even prepare something for that. Last time I looked, the ES6 lesson was a bit short. Also, a few of the newer things were missing. But I have to check again.

It would be brilliant if we could fix a date rather soon. I'll come to Oslo in September anyway, but have yet a flight to book. So there's still some flexibility for me, and I'd really like to contribute in the effort.

**Comment by digitalsadhu** [comment]
This sounds great. Date works for me. Happy to be involved and help out in any way I can.

**Comment by Andersos** [comment]
I'm in =)

**Comment by mewwts** [comment]
Great initiative @plasmacx! Would love to join, but I'll have to sit this one out as unfortunately this date doesn't work for me. Next time. :+1:

**Comment by ghost** [comment]
> ...unfortunately this date doesn't work for me

Noooooooo! So sad ...

By the way, the flight is booked now. I'll start preparing some material as soon as possible. Let's see if something suitable turns out.

Checklist:
- Find a location
- Create a schedule
- Announce date on Meetup
- Invite more people :yum:

**Comment by ghost** [comment]
Just proposed this to get a bit more attention: http://www.meetup.com/NodeJSOslo/events/224167722/

@Andersos Do you think we could _'abuse'_ the Finn canteen for another event? I found it very nice there the last two times, also quite central.

**Comment by Andersos** [comment]
Unfortunately I don't work for Finn anymore but it is a nice place and I am sure if we can find somebody that can be the person in charge we can definitively use the Canteen =)

**Comment by ghost** [comment]
Now I'm courious how that happened!

Maybe someone from the Meetup group will pick it up. I'm a bit afraid of Teknologihuset for it seems to be rather expensive, even for a half day. The thought of sharing the costs for the room among maybe 20 to 30 attendees doesn't really appeal to me.

**Comment by Andersos** [comment]
If you do it at night it is free no?
