### ISSUE TITLE
NodeSchool International Day Norway

### ISSUE THREAD

**Issue by asbjornenge** [nodeschool/oslo#4]
Are you guys doing anything for http://nodeschool.io/international-day/ ? We here in Stavanger are! Maybe we should have a video-link open or something? Feels like we are more ppl :stuck_out_tongue:

**Comment by Andersos** [comment]
@mewwts was talking about having another NodeSchool event and I suggested to have it on the International day in https://github.com/nodeschool/oslo/issues/3. If we arrange one for that day it would be fun to set up a video stream =)

**Comment by asbjornenge** [comment]
@Andersos ping me if it happens :+1:

**Comment by mewwts** [comment]
There's oneshot at that day in Oslo however, https://github.com/oneshot/oslo. Dunno if you guys plan to attend? @Andersos

**Comment by Andersos** [comment]
Unfortunately I wont be in Oslo for that day =(

**Comment by Andersos** [comment]
So no International day for us. If you didn't attend OneShot Oslo check out the videos here: https://www.youtube.com/channel/UCtgoZLrun9SR1_m3itSYbIA
