### ISSUE TITLE
Nodeschool-no organization established

### ISSUE THREAD

**Issue by leftieFriele** [nodeschool/oslo#6]
I created a GitHub group called [Nodeschool-no](https://github.com/nodeschool-no), it was inspired by [Nodeschool-ja](https://github.com/nodeschool-ja).
The reason I did it was to enable easier collaboration on translation efforts. Right now you need to fork repos and doing that on personal repos is a bit of a pain and it makes collaboration harder than it has to. Therefor I created this GitHub org to enable easier collaboration.

**Comment by maciejczyzewski** [comment]
Fancy idea :+1: How can I become a member of this group? :smile: 
![applause](http://gifs.joelglovier.com/clap/applause.gif)
_We should do webpage and logo of Norway/Oslo._

**Comment by leftieFriele** [comment]
@maciejczyzewski you can just say so here :) the general purpose is to make it easier to collaborate on Norwegian translations of Nodeschool material. if you want to help out just let me know

**Comment by maciejczyzewski** [comment]
Of course I can help! But I would rather making webpage and logo, because other countries/cities have. @leftieFriele

**Comment by digitalsadhu** [comment]
A website for nodeschool or translations?

**Comment by maciejczyzewski** [comment]
For nodeschool, of course! @digitalsadhu

**Comment by digitalsadhu** [comment]
Oh yea we don't have one yet!

**Comment by leftieFriele** [comment]
I'm not sure we need a website for the nodeschool-no as its intended to be a group for just collaboration and github is sufficient for that I think.

**Comment by maciejczyzewski** [comment]
In my imagination I see the page where in one place you have all important information about: 
- other cities in Norway (Stavanger, Bergen)
- logo and information
- future events (calendar)
- link to group at Github (translations and main repo)
- tasks to do :notebook: 

> It is better to gather all the information in one place. :smile: 

P.S Add me to group...

**Comment by leftieFriele** [comment]
I added you @maciejczyzewski

**Comment by Andersos** [comment]
Is http://nodeschool.io/nb-no/ not sufficient?

**Comment by maciejczyzewski** [comment]
@Andersos it's only a translation.

**Comment by zo0o0ot** [comment]
FYI, [Nodeschool London](https://github.com/nodeschool/london/tree/gh-pages) has a nice site template. I used it as a base when I created the [Nodeschool Wisconsin site](http://nodeschool.io/wisconsin/).

**Comment by leftieFriele** [comment]
@zo0o0ot thanks for the tip about the site template, it looked like a great starting point.
